package com.rohit.model;
// Generated Jun 16, 2017 6:57:48 PM by Hibernate Tools 4.0.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "eventregistration")
public class City implements java.io.Serializable {


  private String cityId;
  private String cityName;
  private Set events = new HashSet(0);

  public City() {}


  public City(String cityId, String cityName) {
    this.cityId = cityId;
    this.cityName = cityName;
  }

  public City(String cityId, String cityName, Set events) {
    this.cityId = cityId;
    this.cityName = cityName;
    this.events = events;
  }

  @Id


  @Column(name = "CITY_ID", unique = true, nullable = false, length = 45)
  public String getCityId() {
    return this.cityId;
  }

  public void setCityId(String cityId) {
    this.cityId = cityId;
  }


  @Column(name = "CITY_NAME", nullable = false, length = 45)
  public String getCityName() {
    return this.cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
  public Set getEvents() {
    return this.events;
  }

  public void setEvents(Set events) {
    this.events = events;
  }



}


