package com.rohit.model;
// Generated Jun 16, 2017 6:57:48 PM by Hibernate Tools 4.0.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "eventregistration")
public class Employee implements java.io.Serializable {


  private String empId;
  private String empFirstName;
  private String empLastName;
  private Set<RolesDefination> rolesDefinations = new HashSet<>(0);

  public Employee() {}


  public Employee(String empId) {
    this.empId = empId;
  }

  public Employee(String empId, String empFirstName, String empLastName, Set<RolesDefination> rolesDefinations) {
    this.empId = empId;
    this.empFirstName = empFirstName;
    this.empLastName = empLastName;
    this.rolesDefinations = rolesDefinations;
  }

  @Id


  @Column(name = "EMP_ID", unique = true, nullable = false, length = 45)
  public String getEmpId() {
    return this.empId;
  }

  public void setEmpId(String empId) {
    this.empId = empId;
  }


  @Column(name = "EMP_FIRST_NAME", length = 45)
  public String getEmpFirstName() {
    return this.empFirstName;
  }

  public void setEmpFirstName(String empFirstName) {
    this.empFirstName = empFirstName;
  }


  @Column(name = "EMP_LAST_NAME", length = 45)
  public String getEmpLastName() {
    return this.empLastName;
  }

  public void setEmpLastName(String empLastName) {
    this.empLastName = empLastName;
  }

  
  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "roles_employee", catalog = "eventregistration",
      joinColumns = {@JoinColumn(name = "EMP_ID", nullable = false, updatable = false)},
      inverseJoinColumns = {@JoinColumn(name = "ROLE_ID", nullable = false, updatable = false)})
  public Set<RolesDefination> getRolesDefinations() {
    return this.rolesDefinations;
  }

  public void setRolesDefinations(Set<RolesDefination> rolesDefinations) {
    this.rolesDefinations = rolesDefinations;
  }



}


