package com.rohit.model;
// Generated Jun 16, 2017 6:57:48 PM by Hibernate Tools 4.0.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "eventregistration",
    uniqueConstraints = @UniqueConstraint(columnNames = "EVENT_SLOT_NO"))
public class Event implements java.io.Serializable {


  private String eventId;
  private City city;
  private String eventName;
  private Date eventStartTime;
  private Date eventEndTime;
  private int eventSlotNo;
  private int eventSlotCapacity;

  public Event() {}

  public Event(String eventId, City city, String eventName, Date eventStartTime, Date eventEndTime,
      int eventSlotNo, int eventSlotCapacity) {
    this.eventId = eventId;
    this.city = city;
    this.eventName = eventName;
    this.eventStartTime = eventStartTime;
    this.eventEndTime = eventEndTime;
    this.eventSlotNo = eventSlotNo;
    this.eventSlotCapacity = eventSlotCapacity;
  }

  @Id


  @Column(name = "EVENT_ID", unique = true, nullable = false, length = 45)
  public String getEventId() {
    return this.eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "CITY_ID", nullable = false)
  public City getCity() {
    return this.city;
  }

  public void setCity(City city) {
    this.city = city;
  }


  @Column(name = "EVENT_NAME", nullable = false, length = 45)
  public String getEventName() {
    return this.eventName;
  }

  public void setEventName(String eventName) {
    this.eventName = eventName;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "EVENT_START_TIME", nullable = false, length = 19)
  public Date getEventStartTime() {
    return this.eventStartTime;
  }

  public void setEventStartTime(Date eventStartTime) {
    this.eventStartTime = eventStartTime;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "EVENT_END_TIME", nullable = false, length = 19)
  public Date getEventEndTime() {
    return this.eventEndTime;
  }

  public void setEventEndTime(Date eventEndTime) {
    this.eventEndTime = eventEndTime;
  }


  @Column(name = "EVENT_SLOT_NO", unique = true, nullable = false)
  public int getEventSlotNo() {
    return this.eventSlotNo;
  }

  public void setEventSlotNo(int eventSlotNo) {
    this.eventSlotNo = eventSlotNo;
  }


  @Column(name = "EVENT_SLOT_CAPACITY", nullable = false)
  public int getEventSlotCapacity() {
    return this.eventSlotCapacity;
  }

  public void setEventSlotCapacity(int eventSlotCapacity) {
    this.eventSlotCapacity = eventSlotCapacity;
  }



}


