package com.rohit.model;
// Generated Jun 16, 2017 6:57:48 PM by Hibernate Tools 4.0.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * RolesDefination generated by hbm2java
 */
@Entity
@Table(name = "roles_defination", catalog = "eventregistration")
public class RolesDefination implements java.io.Serializable {


  private String roleId;
  private String roleDescription;
  private Set employees = new HashSet(0);

  public RolesDefination() {}


  public RolesDefination(String roleId, String roleDescription) {
    this.roleId = roleId;
    this.roleDescription = roleDescription;
  }

  public RolesDefination(String roleId, String roleDescription, Set employees) {
    this.roleId = roleId;
    this.roleDescription = roleDescription;
    this.employees = employees;
  }

  @Id


  @Column(name = "ROLE_ID", unique = true, nullable = false, length = 45)
  public String getRoleId() {
    return this.roleId;
  }

  public void setRoleId(String roleId) {
    this.roleId = roleId;
  }


  @Column(name = "ROLE_DESCRIPTION", nullable = false, length = 45)
  public String getRoleDescription() {
    return this.roleDescription;
  }

  public void setRoleDescription(String roleDescription) {
    this.roleDescription = roleDescription;
  }

  @ManyToMany(fetch = FetchType.LAZY, mappedBy = "rolesDefinations")
  public Set getEmployees() {
    return this.employees;
  }

  public void setEmployees(Set employees) {
    this.employees = employees;
  }



}


